# Generated by Django 2.0.3 on 2018-03-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trends',
            name='target_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
